services:
  - type: web
    name: igf-app
    env: node
    plan: free
    buildCommand: |
      npm ci
    startCommand: |
      npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      # If you ever want to restrict CORS in server.js, point to your site origin:
      - key: CORS_ORIGIN
        value: "*"
